import { Theme, ButtonStyleProps, ButtonSizeProps, ButtonVariant, ButtonState, ButtonSize } from "@ui/theme.slint";
import { Router } from "gen/router.slint";
import { GwBridge, IdentityDraft } from "gw-bridge.slint";
import { Cyber } from "cyber.slint";

export { Theme, ButtonStyleProps, ButtonSizeProps, ButtonVariant, ButtonState, ButtonSize }
export { GwBridge, IdentityDraft }
export * from "gen/exports.slint";

export component AppWindow inherits Window {
    title: "groundwire";
    preferred-width: 480px;
    preferred-height: 800px;
    background: Cyber.page-bg;

    Router { }
}
